### ISSUE TITLE
Use BetterBackdoor Over WAN Without Port Forwarding

### ISSUE THREAD

**Issue by miladzero** [ThatcherDev/BetterBackdoor#14]
Use BetterBackdoor Over WAN Without Port Forwarding ??

**Comment by ThatcherDev** [comment]
Currently, BetterBackdoor only works in a local network so it would not be able to work over WAN.

**Comment by miladzero** [comment]
> Currently, BetterBackdoor only works in a local network so it would not be able to work over WAN.

Please add this feature Over WAN Without Port Forwarding 👈🙏🙏

**Comment by ThatcherDev** [comment]
In Java, Sockets cannot operate over WAN without port forwarding but I will look into another solution to achieve your request.

**Comment by miladzero** [comment]
Thanks You , I'm waiting for the update

**Comment by ThatcherDev** [comment]
After extensive research, It seems like there is no way to have two Java processes communicate over WAN without using port forwarding. This is because the attacker must start a server for the client to connect to. In order for this server to be connected to over WAN, it must be forwarded to the public IP address and this involves port forwarding. I am sorry that I am not able to add your requested feature. If it helps, I will be adding WAN support with port forwarding, however this cannot be done without port forwarding.
