### ISSUE TITLE
Multiple sessions

### ISSUE THREAD

**Issue by FacuBayo** [ThatcherDev/BetterBackdoor#22]
Is it possible to get multiple sessions of the victims? I mean, use more than one infected computer at the same time

**Comment by ThatcherDev** [comment]
Currently, no. however, this sounds like an interesting feature. if it was to be implemented you would be able to select the computer to control when running 1 at the main menu. i will look into adding this!

**Comment by ThatcherDev** [comment]
Good news! As of version 1.12.0, multiple sessions is supported. If multiple clients attempt to connect to the attacking computer, the user is prompted to select which client to connect to. However your idea of 

> using more than one infected computer at the same time

is not going to be implemented because some of the commands are computer specific, meaning that running one command on one computer might not work on another.
